### PR TITLE
Use cljs.main

### LINKED ISSUE #34: errors when using web-worker builds
Some fail messages in the JS console

image

There are random fail messages on recompile / reload

### PR DESCRIPTION
**Pull request by roman01la**
Resolves #34

This PR replaces figwheel with cljs.main

- `clj -A:repl` starts application REPL
- `clj -A:worker` starts worker build

### CODE REVIEW

File: src/replete/editor.cljs [hunk 1]
```diff
@@ -45,7 +45,7 @@
      [[cmirror-edit-box ed-opts cmirror-opts style]
       [button
        :class "btn-primary"
-       :label (str "Eval")
+       :label (str "aEval")
```
Comment (raymcdermott) [inline src/replete/editor.cljs:48]: Not sure what this means ... async? Is it meaningful for users?

**Review by raymcdermott — APPROVED** [review]
